### PR TITLE
Proposal for unique header names

### PR DESCRIPTION
**Pull request by osiegmar**
Multiple headers with the same name are problematic to handle when reading the file. What do you think of this additional SHOULD clause?

### CODE REVIEW

**Comment by nightwatchcyber** [comment]
I don't think we can mandate uniqueness, some packages may process by column position instead of name.

**Comment by osiegmar** [comment]
Right, hence the **SHOULD**.

**Comment by osiegmar** [comment]
Oh, sorry. I wanted to write SHOULD but have not. Would SHOULD be ok?

**Comment by nightwatchcyber** [comment]
> Oh, sorry. I wanted to write SHOULD but have not. Would SHOULD be ok?

I don't think SHOULD is correct here - it indicates a preference for one approach vs. the other. Perhaps, a more correct thing would be to let people know about this without picking one over the other. Maybe something like:

> Implementers should be aware that some applications may treat header values as unique

I am also planning to add a section to the RFC explaining the overall CSV design including delimeters, quotes, etc.

**Comment by nightwatchcyber** [comment]
Looks good, you may want to refresh the origin

**Pull request merged**
